/* ELIMINAZIONE TABELLE */

DROP TABLE BIBLIOTECA IF EXISTS;
DROP TABLE RECAPITOTELEFONICO IF EXISTS;
DROP TABLE IMMAGINE IF EXISTS;
DROP TABLE POSTOLETTURA IF EXISTS;
DROP TABLE LIBRO IF EXISTS;
DROP TABLE LIBROCARTACEO IF EXISTS;
DROP TABLE EBOOK IF EXISTS;
DROP TABLE UTENTE IF EXISTS;
DROP TABLE AMMINISTRATORE IF EXISTS;
DROP TABLE AUTORE IF EXISTS;
DROP TABLE VOLONTARIO IF EXISTS;
DROP TABLE UTILIZZATORE IF EXISTS;
DROP TABLE MESSAGGIO IF EXISTS;
DROP TABLE SEGNALAZIONE IF EXISTS;
DROP TABLE LISTA IF EXISTS;
DROP TABLE VISITA IF EXISTS;
DROP TABLE REGISTRAZIONE IF EXISTS;
DROP TABLE PRENOTAZIONE IF EXISTS;
DROP TABLE CONSEGNA IF EXISTS;
DROP TABLE REGISTRAZIONE IF EXISTS;




