/* ELIMINAZIONE TABELLE E TRIGGER E VIEW */
DROP VIEW IF EXISTS getPrenotazione;
DROP TRIGGER IF EXISTS CambioStatoConsegnatoPrenotato ON consegna;
DROP TRIGGER IF EXISTS CambioStatoDisponibileConsegnato ON prenotazione;
DROP TRIGGER IF EXISTS CambioStatoPrenotatoConsegnato ON consegna;
DROP TRIGGER IF EXISTS CambiaStatoAttivoSospeso ON segnalazione;

DROP MATERIALIZED VIEW IF EXISTS classificaBibliotecaPostiLettura;
DROP MATERIALIZED VIEW IF EXISTS classificaEbookAcceduti;
DROP MATERIALIZED VIEW IF EXISTS classificaLibriCartacei;
DROP MATERIALIZED VIEW IF EXISTS classificaVolontari;
DROP MATERIALIZED VIEW IF EXISTS ClustersUtilizzatori;

DROP TABLE IF EXISTS MESSAGGIO;
DROP TABLE IF EXISTS SEGNALAZIONE;
DROP TABLE IF EXISTS VISITA;
DROP TABLE IF EXISTS LISTA;
DROP TABLE IF EXISTS IMMAGINE;
DROP TABLE IF EXISTS RECAPITOTELEFONICO;
DROP TABLE IF EXISTS AMMINISTRATORE;
DROP TABLE IF EXISTS AUTORE;
DROP TABLE IF EXISTS REGISTRAZIONE;
DROP TABLE IF EXISTS CONSEGNA;
DROP TABLE IF EXISTS VOLONTARIO;
DROP TABLE IF EXISTS POSTOLETTURA;
DROP TABLE IF EXISTS PRENOTAZIONE;
DROP TABLE IF EXISTS UTILIZZATORE;
DROP TABLE IF EXISTS UTENTE;
DROP TABLE IF EXISTS EBOOK;
DROP TABLE IF EXISTS LIBROCARTACEO;
DROP TABLE IF EXISTS LIBRO;
DROP TABLE IF EXISTS BIBLIOTECA;